name: 中南民族大学
code: scuec
sources:
- name: 教务处-管理文件
  type: web
  list_url: https://www.scuec.edu.cn/jwc/glwj.htm
  url_pattern: null
  max_pages: 1
  enabled: true
  crawl_mode: incremental
  max_age_days: null
  fetch_detail: true
  deep_check: false
- name: 教务处-办事指南
  type: web
  list_url: https://www.scuec.edu.cn/jwc/bszn.htm
  url_pattern: null
  max_pages: 1
  enabled: true
  crawl_mode: incremental
  max_age_days: null
  fetch_detail: true
  deep_check: false
- name: 学校主页-学校通知公告
  type: web
  list_url: https://www.scuec.edu.cn/sylm/tzgg.htm
  url_pattern: jwc/info/\d+/\d+\.htm
  max_pages: 3
  enabled: true
  crawl_mode: incremental
  max_age_days: 30
  fetch_detail: true
  deep_check: false
- name: 电子信息工程学院-通知公告
  type: web
  list_url: https://dxxy.scuec.edu.cn/index/tzgg.htm
  url_pattern: null
  max_pages: 1
  enabled: true
  crawl_mode: incremental
  max_age_days: 30
  fetch_detail: true
  deep_check: false
- name: 党委学生工作部-规章制度
  type: web
  list_url: https://www.scuec.edu.cn/stu/index/gzzd.htm
  url_pattern: null
  max_pages: 20
  enabled: true
  crawl_mode: incremental
  max_age_days: null
  fetch_detail: true
  deep_check: false
- name: 党政办公室-通知公告
  type: web
  list_url: https://www.scuec.edu.cn/xb/index/tzgg.htm
  url_pattern: null
  max_pages: 5
  enabled: true
  crawl_mode: incremental
  max_age_days: null
  fetch_detail: true
  deep_check: false
